### PR TITLE
Reimburse tankbottoms.eth for jmill work

### PR DESCRIPTION
**Pull request by aeolianeth**

### CODE REVIEW

**Comment by tankbottoms** [comment]
🍌 proposal to reimburse tankbottoms $5,000(in ETH) for past jmill reimbursement

(May 14, 2022)

action

-   reimburse tankbottoms.eth 0x5d95baEBB8412AD827287240A5c281E3bB30d27E for prior weeks of payment to jmill. US5,000(in ETH).
-   amount reflects jmill's estimates sans non-peel activity

rationale

-   transaction-hashes from etherscan
    -   https://etherscan.io/tx/0x25e37ed285eb4e9387375e5a57da39ba0333449cff5e7d7386843b2e9c47beed
    -   https://etherscan.io/tx/0xae38e81be6c40f87ac9ecdbe936abfbc7e225831be851b6ca95f7f140d4b9c2f
-   references to previous discord discussions
    -   https://discord.com/channels/939317843059679252/974852790054690886/974853250178248864

additional discussions

-   https://discord.com/channels/775859454780244028/942522503258054686/966831596198051880
-   https://discord.com/channels/775859454780244028/942522503258054686/966835218994561045
-   https://discord.com/channels/775859454780244028/942522503258054686/968141363629674516
-   https://discord.com/channels/775859454780244028/942522503258054686/968652992452628521

support for jmill's work

-   https://discord.com/channels/939317843059679252/940436144997433356/970447513477865564

risks

-   tankbottoms' feelings are hurt and he follows up all future posts with a cartoon of a puppy dog with sad eyes
-   tankbottoms' uses the funds to level up Peel's discord with stickers of vegetables and fruits without traditional peels, thereby offending the community
-   tankbottoms' pretends to not have understood that retroactive reimbursements are not favored and does this continuously just to be annoying
-   jmills turns out to be a complete knob and actually subtracts value thereby being a complete waste of time and ETH

cc @Peeler (core team)

**Comment by tankbottoms** [comment]
updated the proposal slightly. still contains the core points.

**Comment by aeolianeth** [comment]
@tankbottoms thanks for the updates - I added them to the PR!

Also added you as a collaborator to the GitHub repo - you should be able to push changes directly to this branch now 🙏

**Comment by aeolianeth** [comment]
Adding my support for this proposal ✅  

(I'm the author of the PR and can't approve it)

**Review by johnnyd-eth — APPROVED** [review]

**Review by peripheralist — APPROVED** [review]
IMO the risks listed here are simply too critical to ignore and must be mitigated at all costs.

(thank you @tankbottoms, approving)

**Pull request merged**
